### ISSUE TITLE
Error shebang

### ISSUE THREAD

**Issue by jafamo** [creawww/docker-rails-mysql#1]
Tengo una app con Ruby&Rails y me gustaría poder incluirla en un docker para poder hacer pruebas.

Al ejecutar este comando en otra terminal, 
`docker exec -it --user $UID:$UID drails rails new . -d mysql`

me sale este error:
```
/usr/local/bin/ruby: warning: shebang line ends with \r may cause a problem
Can't initialize a new Rails application within the directory of another, please change to a non-Rails directory first.
Type 'rails' for help.
```

Un saludo.

**Comment by creawww** [comment]
este docker lo tengo algo abandonado el que usamos para rails es 

https://github.com/creawww/ruby-docker

un solo contenedor con sqllite, prueba con este

**Comment by jafamo** [comment]
Me interesaba este porque ya viene con el MySQL. No tengo demasiados conocimientos en Docker, ¿ es posible una versión con MySQL del contenedor sin el SQLite ?
Un saludo
